#!/usr/bin/env node
/* ───────────────────────────────────────────────────────────────────────────
   Pull Figma colour + text styles (and component list) into the repo, so the
   design system stays in sync without a manual fetch/export. Run by CI
   (.github/workflows/figma-sync.yml) or locally:

     FIGMA_TOKEN=xxx FIGMA_FILE_KEY=yyy node scripts/figma-sync.mjs

   Writes:
     app/tokens/figma-tokens.json          — snapshot (name → value)
     css/figma-tokens.generated.css        — :root overrides (opt-in @import)
   The Action commits these when they change.
   ─────────────────────────────────────────────────────────────────────────── */
import { writeFileSync, mkdirSync } from 'node:fs';

const TOKEN = process.env.FIGMA_TOKEN;
const KEY = process.env.FIGMA_FILE_KEY;
if (!TOKEN || !KEY) { console.error('FIGMA_TOKEN and FIGMA_FILE_KEY are required'); process.exit(1); }

const H = { 'X-Figma-Token': TOKEN };
const fig = async (p) => { const r = await fetch('https://api.figma.com' + p, { headers: H }); if (!r.ok) throw new Error('figma ' + r.status + ' ' + (await r.text()).slice(0, 200)); return r.json(); };
const hx = (n) => Math.max(0, Math.min(255, Math.round(n * 255))).toString(16).padStart(2, '0');
const toHex = (c) => (c ? '#' + hx(c.r) + hx(c.g) + hx(c.b) : null);

const meta = await fig(`/v1/files/${KEY}?depth=1`);
const styles = ((await fig(`/v1/files/${KEY}/styles`)).meta || {}).styles || [];
const ids = styles.map((s) => s.node_id).filter(Boolean).slice(0, 120);
const nodes = ids.length ? (await fig(`/v1/files/${KEY}/nodes?ids=${encodeURIComponent(ids.join(','))}`)).nodes || {} : {};

const colors = styles.filter((s) => s.style_type === 'FILL').map((s) => {
  const d = nodes[s.node_id] && nodes[s.node_id].document;
  const f = ((d && d.fills) || []).find((x) => x.type === 'SOLID');
  return { name: s.name, hex: f && f.color ? toHex(f.color) : null };
}).filter((c) => c.hex);

const text = styles.filter((s) => s.style_type === 'TEXT').map((s) => {
  const st = nodes[s.node_id] && nodes[s.node_id].document && nodes[s.node_id].document.style;
  return st ? { name: s.name, family: st.fontFamily || null, size: st.fontSize ? Math.round(st.fontSize) : null, weight: st.fontWeight || null } : null;
}).filter(Boolean);

let components = [];
try { components = (((await fig(`/v1/files/${KEY}/components`)).meta || {}).components || []).map((c) => ({ name: c.name, key: c.key, updated: c.updated_at || null })); } catch (e) { /* none published */ }

mkdirSync('app/tokens', { recursive: true });
writeFileSync('app/tokens/figma-tokens.json', JSON.stringify({ file: { name: meta.name, lastModified: meta.lastModified, key: KEY }, colors, text, components, syncedAt: new Date().toISOString() }, null, 2) + '\n');
writeFileSync('css/figma-tokens.generated.css', '/* generated by scripts/figma-sync.mjs — Figma colour styles as CSS vars */\n:root{\n' + colors.map((c) => '  --' + c.name.replace(/\s+/g, '') + ': ' + c.hex + ';').join('\n') + '\n}\n');
console.log(`Figma sync: ${colors.length} colours, ${text.length} text styles, ${components.length} components.`);
